Repository discordjs/voice, pull requests merged in 2021-06, with the labels that each got.

#105 refactor(Adapter): sendPayload now returns boolean
  .npmrc
  examples/basic/adapter.ts
  package-lock.json
  package.json
  src/VoiceConnection.ts
  src/__tests__/VoiceConnection.test.ts
  src/audio/AudioResource.ts
  src/audio/__tests__/AudioPlayer.test.ts
  src/audio/__tests__/AudioResource.test.ts
  src/networking/__tests__/VoiceUDPSocket.test.ts
  src/receive/__tests__/VoiceReceiver.test.ts
  src/receive/__tests__/fixtures/rtp.ts
  src/util/adapter.ts
Labels: semver:major

#109 chore(Deps): update dependencies
  .eslintrc.json
  package-lock.json
  package.json
  src/VoiceConnection.ts
  src/audio/AudioPlayer.ts
  src/networking/Networking.ts
  src/networking/VoiceUDPSocket.ts
  src/networking/VoiceWebSocket.ts
  src/networking/__tests__/VoiceUDPSocket.test.ts
  src/receive/SSRCMap.ts
Labels: dependencies, semver:patch

#110 feat(AudioResource): add encoder property, fix type for metadata
  examples/music-bot/src/bot.ts
  examples/music-bot/src/music/subscription.ts
  src/audio/AudioResource.ts
  src/audio/__tests__/AudioPlayer.test.ts
  src/audio/__tests__/AudioResource.test.ts
Labels: semver:minor

#111 chore(Legal): added UNLICENSE in examples
  examples/UNLICENSE
  package.json
Labels: chore

#114 chore(Deps): update discord.js dep in music bot example
  examples/music-bot/package.json
  examples/music-bot/src/bot.ts
  examples/music-bot/src/music/adapter.ts
Labels: documentation

#118 feat(Util): add Opus audio probing utility
  examples/music-bot/README.md
  examples/music-bot/package.json
  examples/music-bot/src/music/track.ts
  examples/music-bot/tsconfig.json
  package-lock.json
  package.json
  src/util/__tests__/demuxProbe.test.ts
  src/util/demuxProbe.ts
  src/util/index.ts
Labels: semver:minor

#120 feat!: add silence padding frames to AudioResources
  src/audio/AudioPlayer.ts
  src/audio/AudioResource.ts
  src/audio/__tests__/AudioPlayer.test.ts
  src/audio/__tests__/AudioResource.test.ts
Labels: semver:major

#121 feat: allow awaitable void event listeners, fix VoiceConnection disconnected states
  examples/music-bot/src/music/subscription.ts
  src/VoiceConnection.ts
  src/audio/AudioPlayer.ts
  src/index.ts
  src/networking/Networking.ts
  src/networking/VoiceUDPSocket.ts
  src/networking/VoiceWebSocket.ts
  src/receive/SSRCMap.ts
  src/util/util.ts
Labels: semver:minor

#129 feat!(VoiceConnection): add disconnect and rename reconnect to rejoin
  examples/music-bot/src/music/subscription.ts
  src/VoiceConnection.ts
  src/__tests__/VoiceConnection.test.ts
Labels: semver:major

#130 feat(Secretbox): throw fallback error when no encryption package installed
  src/util/Secretbox.ts
  src/util/__tests__/Secretbox.test.ts
Labels: semver:patch

#131 refactor(Secretbox): type `methods` object
  src/util/Secretbox.ts
Labels: refactor

#127 docs(Examples): add a JavaScript example
  examples/README.md
  examples/radio-bot/.gitignore
  examples/radio-bot/README.md
  examples/radio-bot/config.example.json
  examples/radio-bot/index.js
  examples/radio-bot/package.json
Labels: documentation

#139 fix(VoiceConnection): stuck on signalling state when rejoining the same channel on ready state
  src/VoiceConnection.ts
  src/__tests__/VoiceConnection.test.ts
Labels: semver:patch

#140 fix(VoiceConnection): disconnect method now actually disconnects
  src/VoiceConnection.ts
  src/__tests__/VoiceConnection.test.ts
Labels: semver:patch
