Repository discordjs/voice, pull requests merged in 2021-02, with the labels that each got.

#10 feat!: ability to set AudioPlayer behaviours
  src/audio/AudioPlayer.ts
Labels: semver:major

#13 feat: debugging utilities
  package-lock.json
  package.json
  src/VoiceConnection.ts
  src/audio/AudioPlayer.ts
  src/index.ts
  src/networking/Networking.ts
  src/networking/VoiceWebSocket.ts
  src/util/generateDependencyReport.ts
Labels: semver:minor

#18 deps: remove peer dependencies
  README.md
  package-lock.json
  package.json
Labels: dependencies, semver:major

#16 refactor(DataStore): hook into WebSocketManager
  package-lock.json
  package.json
  src/DataStore.ts
  src/VoiceConnection.ts
Labels: refactor, semver:patch

#20 feat(AudioPlayer): throw when playing ended audio
  src/audio/AudioPlayer.ts
Labels: semver:patch

#19 feat!: ability to unsubscribe connections from audio players
  examples/basic.ts
  src/VoiceConnection.ts
  src/audio/AudioPlayer.ts
  src/audio/PlayerSubscription.ts
Labels: semver:major

#26 chore(deps): move @types/* and dapi-types to dev deps
  package-lock.json
  package.json
Labels: dependencies, semver:patch

#24 feat: export all public types
  src/audio/index.ts
  src/index.ts
  src/joinVoiceChannel.ts
  src/util/index.ts
Labels: semver:minor

#28 fix(VoiceConnection): correctly compare subscriptions in state transition
  src/VoiceConnection.ts
Labels: semver:patch

#25 docs: include a better starter example
  examples/basic.ts
  examples/basic/README.md
  examples/basic/basic-example.ts
  examples/basic/util.ts
  package-lock.json
Labels: documentation

#22 feat(AudioPlayer): allow playing streams that are not yet readable
  src/audio/AudioPlayer.ts
Labels: semver:minor

#32 feat(AudioPlayer): propagate stream errors
  src/audio/AudioPlayer.ts
Labels: semver:patch

#33 chore(*): repo update/changes
  .eslintignore
  .eslintrc.json
  .gitattributes
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/test.yml
  .gitignore
  .npmrc
  .prettierrc.json
  LICENSE
  README.md
  examples/basic/README.md
  examples/basic/basic-example.ts
  examples/basic/util.ts
  package-lock.json
  package.json
  src/DataStore.ts
  src/VoiceConnection.ts
  src/audio/AudioPlayer.ts
  src/audio/AudioResource.ts
  src/audio/TransformerGraph.ts
  src/audio/index.ts
  src/index.ts
  src/joinVoiceChannel.ts
  src/networking/Networking.ts
  src/networking/VoiceWebSocket.ts
  src/util/Secretbox.ts
  src/util/generateDependencyReport.ts
  tsconfig.eslint.json
  tsconfig.json
Labels: chore

#37 feat(AudioResource): make createAudioResource options optional
  src/audio/AudioResource.ts
Labels: semver:minor

#35 fix(VoiceConnection): unsubscribing + moving channels
  src/VoiceConnection.ts
Labels: semver:patch

#39 feat(AudioPlayer): make createAudioPlayer options optional
  src/audio/AudioPlayer.ts
Labels: semver:minor

#38 chore(GitHub): remove typings line from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#42 feat: entersState helper function
  examples/basic/README.md
  examples/basic/basic-example.ts
  src/util/entersState.ts
  src/util/index.ts
Labels: semver:minor

#45 refactor(TransformerGraph): extra constraint satisfaction
  src/audio/AudioResource.ts
  src/audio/TransformerGraph.ts
Labels: refactor

#49 refactor(AudioResource): implement locking
  src/audio/AudioPlayer.ts
  src/audio/AudioResource.ts
Labels: refactor, semver:patch

#47 feat(TransformerGraph): add FFmpeg opus optimization
  src/audio/TransformerGraph.ts
Labels: semver:patch

#51 chore: add CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: chore

#58 fix(VoiceConnection): improve recoverability
  src/VoiceConnection.ts
Labels: priority:high, semver:patch

#59 feat(AudioPlayer): add maxMissedFrames behaviour
  src/audio/AudioPlayer.ts
Labels: semver:minor

#55 refactor: use global timer for audio players
  src/DataStore.ts
  src/audio/AudioPlayer.ts
Labels: refactor, semver:patch

#67 chore(README): add badges
  README.md
Labels: chore

#66 feat!: implement adapters
  examples/basic/README.md
  examples/basic/adapter.ts
  examples/basic/basic-example.ts
  package-lock.json
  package.json
  src/DataStore.ts
  src/VoiceConnection.ts
  src/joinVoiceChannel.ts
  src/util/adapter.ts
  src/util/generateDependencyReport.ts
  src/util/index.ts
Labels: semver:major
